---
liferay_download_path: "~/liferay_files/liferay/"
undertow_download_path: "~/liferay_files/undertow/"

liferay_local_path: "~/liferay_files/liferay"
undertow_local_path: "~/liferay_files/undertow"

# If you want download from official websites set use_remote_links: true
use_remote_links: true

#Liferay
dependences_url: https://github.com/liferay/liferay-portal/releases/download/7.2.1-ga2/liferay-ce-portal-dependencies-7.2.1-ga2-20191111141448326.zip
osgi_url: https://github.com/liferay/liferay-portal/releases/download/7.2.1-ga2/liferay-ce-portal-osgi-7.2.1-ga2-20191111141448326.zip
portal_url: https://github.com/liferay/liferay-portal/releases/download/7.2.1-ga2/liferay-ce-portal-7.2.1-ga2-20191111141448326.war
#Undertow
websocket_url: https://repo1.maven.org/maven2/io/undertow/undertow-websockets-jsr/2.0.23.Final/undertow-websockets-jsr-2.0.23.Final.jar
servlet_url: https://repo1.maven.org/maven2/io/undertow/undertow-servlet/2.0.23.Final/undertow-servlet-2.0.23.Final.jar
core_url: https://repo1.maven.org/maven2/io/undertow/undertow-core/2.0.23.Final/undertow-core-2.0.23.Final.jar
