---
- name: Install Unzip
  apt:
    name: unzip
    update_cache: yes
- name: Create folder /opt/wildfly/modules/com/liferay/portal/main
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/wildfly/modules
    - /opt/wildfly/modules/com
    - /opt/wildfly/modules/com/liferay
    - /opt/wildfly/modules/com/liferay/portal
    - /opt/wildfly/modules/com/liferay/portal/main
- name: Remove all files
  file:
    path: /opt/wildfly/modules/com/liferay/portal/main/
    state: absent
- name: Create directory /opt/wildfly/modules/com/liferay/portal/main
  file:
    path: /opt/wildfly/modules/com/liferay/portal/main
    state: directory
- name: Unzip dependences
  unarchive:
    remote_src: yes
    src: "{{ liferay_download_path }}/liferay-ce-portal-dependencies*.zip"
    dest: /opt/wildfly/modules/com/liferay/portal/main
- name: Move dependences to main
  shell: mv /opt/wildfly/modules/com/liferay/portal/main/l*/* /opt/wildfly/modules/com/liferay/portal/main && rmdir /opt/wildfly/modules/com/liferay/portal/main/liferay-ce-portal-dependencies-*
- name: Create folder for PSQL driver
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/wildfly/modules/org
    - /opt/wildfly/modules/org/postgres
    - /opt/wildfly/modules/org/postgres/main
- name: Move PSQL driver
  shell: cp ~/postgresql-42.2.8.jar /opt/wildfly/modules/org/postgres/main/postgresql.jar
- name: Create module.xml file for driver
  template:
    src: module_tmplt.j2
    dest: /opt/wildfly/modules/org/postgres/main/module.xml
- name: Create module.xml file for liferay
  lineinfile:
    create: true
    path: /opt/wildfly/modules/com/liferay/portal/main/module.xml
    line: "{{ item }}"
  with_items:
    "{{ module_xml_list }}"
- name: Unzip OSGi
  shell: "rm -rf /opt/osgi/* && unzip {{ liferay_download_path }}/liferay-ce-portal-osgi-*.zip -d /opt/osgi"
- name: Move osgi to osgi
  shell: mv /opt/osgi/liferay-ce-portal-osgi-*/* /opt/osgi && rm -rf /opt/osgi/liferay-ce-portal-osgi-*
- name: Modify standalone.xml
  template:
    src: standalone_tmplt.j2
    dest: /opt/wildfly/standalone/configuration/standalone.xml
  vars:
    filter_spec: '<filter-spec value="not(any(match(&quot;WFLYSRV0059&quot;),match(&quot;WFLYEE0007&quot;)))" />'
    deployment_timeout: 'deployment-timeout="600"'
    jsp_config: '<jsp-config development="true" source-vm="1.8" target-vm="1.8" />'
    psql_ip: '134.209.137.88'
- name: Create portal-ext.properties
  lineinfile:
    path: /opt/portal-ext.properties
    line: jdbc.default.jndi.name=java:jboss/datasources/ExampleDS
    create: yes
- name: Delete all old undertow jars
  shell: "rm undertow*"
  args:
    chdir: "{{ item }}"
  with_items:
    - "/opt/wildfly/modules/system/layers/base/io/undertow/websocket/main"
    - "/opt/wildfly/modules/system/layers/base/io/undertow/servlet/main"
    - "/opt/wildfly/modules/system/layers/base/io/undertow/core/main"
- name: Copy new undertow jars
  shell: "cp {{ undertow_download_path }}/undertow-{{ item }}* /opt/wildfly/modules/system/layers/base/io/undertow/{{ item }}/main"
  with_items:
    - "websocket"
    - "servlet"
    - "core"
- name: Edit module.xml
  lineinfile:
    path: /opt/wildfly/modules/system/layers/base/io/undertow/{{ item.path }}/main/module.xml
    regexp: "<resource-root path="
    line: '<resource-root path="undertow-{{ item.name }}-2.0.23.Final.jar"/>'
  with_items:
    - {path: "websocket", name: "websockets-jsr"}
    - {path: "servlet", name: "servlet"}
    - {path: "core", name: "core"}
- name: Edit bin/standalone.conf
  template:
    src: standalone.conf_tmplt.j2
    dest: /opt/wildfly/bin/standalone.conf
  vars:
    min_memory: 2560
    max_memory: 2560
