---

- name: Download & Unzip WildFly
  unarchive:
    remote_src: yes
    src: "{{ download_link }}"
    dest: /opt
- name: Create a symbolic link
  file:
    src: /opt/wildfly-{{ wildfly_version }}.Final
    dest: /opt/wildfly
    state: link
- name: Replacement to <any-address\> [1]
  lineinfile:
    path: /opt/wildfly/standalone/configuration/standalone.xml
    regexp: '<inet-address'
    line: '            <any-address/>'
- name: Replacement to <any-address\> [2]
  lineinfile:
    path: /opt/wildfly/standalone/configuration/standalone.xml
    regexp: '<inet-address'
    line: '            <any-address/>'
- name: Add admin user to WildFly
  shell: "/opt/wildfly/bin/add-user.sh {{admin_username}} {{admin_password}}"
