- name: Remote Download
  when:
    - use_remote_links == true
  block:
    - name: Create download directories
      file:
        path: ~/liferay_files/{{ item }}
        state: directory
      with_items:
        - liferay
        - undertow
    - name: Remote download Liferay dependences, osgi and portal
      get_url:
        url: "{{ item }}"
        dest: "{{ liferay_download_path }}"
      with_items:
        - "{{ dependences_url }}"
        - "{{ osgi_url }}"
        - "{{ portal_url }}"

    - name: Remote download Undertow websocket, servlet and core jars
      get_url:
        url: "{{ item }}"
        dest: "{{ undertow_download_path }}"
      with_items:
        - "{{ websocket_url }}"
        - "{{ servlet_url }}"
        - "{{ core_url }}"

- name: Download from local server
  when:
    - use_remote_links == false
  block:
    - name: Copy Liferay dependences, osgi and portal
      synchronize:
        src: "{{ liferay_local_path }}"
        dest: "{{ liferay_download_path }}"

    - name: Copy Undertow websocket, servlet and core jars
      synchronize:
        src: "{{ undertow_local_path }}"
        dest: "{{ undertow_download_path }}"

- name: Remote download psql driver
  get_url:
    url: https://jdbc.postgresql.org/download/postgresql-42.2.8.jar
    dest: "~"
