---
- name: Cleaning from previous versions
  file:
    path: "/opt/{{ item }}"
    state: absent
  loop:
    - apache-tomcat-*
    - tomcat

- name: Create new group tomcat
  group:
    name: tomcat
    state: present

- name: Create directory tomcat
  file:
    path: "/opt/tomcat/latest"
    state: directory

- name: Create new user tomcat
  user:
    name: tomcat
    group: tomcat
    system: no
    shell: /bin/bash
    createhome: yes
    home: "/opt/tomcat/latest"

- name: Change owner and group directory tomcat
  file:
    path: "/opt/tomcat/{{ item }}"
    state: directory
    owner: tomcat
    group: tomcat
  loop:
    - latest
    - .jenkins

- name: Downloading required tomcat
  get_url:
    url: "{{tomcat_url}}"
    dest: /opt

- name: Extracting downloaded tomcat
  unarchive:
    src: "/opt/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: Renaming tomcat home
  shell: mv /opt/apache-tomcat-{{req_tomcat_ver}}/* /opt/tomcat/latest

- name: Change mode recurse conf
  file:
    path: "/opt/tomcat/latest/conf"
    state: directory
    recurse: yes
    mode: g+r

- name: Change mode conf
  file:
    path: "/opt/tomcat/latest/conf"
    state: directory
    mode: g+x

- name: Change group directory tomcat
  file:
    path: "/opt/tomcat/"
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat

- name: Change group file tomcat
  file:
    path: "/opt/tomcat/latest/{{ item }}"
    state: file
    owner: tomcat
    group: tomcat
  loop:
    - BUILDING.txt
    - CONTRIBUTING.md
    - LICENSE
    - NOTICE
    - README.md
    - RELEASE-NOTES
    - RUNNING.txt

- name: Create setenv.sh
  template:
    src: setenv
    dest: "/opt/tomcat/latest/bin/setenv.sh"

- name: Change group setenv.sh
  file:
    path: "/opt/tomcat/latest/bin/setenv.sh"
    state: file
    owner: tomcat
    group: tomcat
    mode: g+x

- name: Change context.xml
  template:
    src: tomcat_context.xml
    dest: "/opt/tomcat/latest/conf/context.xml"

- name: Configure tomcat.service
  template:
    src: tomcat.service
    dest: "/etc/systemd/system/"

- name: Reload service
  systemd:
    daemon_reload: yes

- name: Start Tomcat service
  systemd:
    name: tomcat
    enabled: yes
    masked: no

- name: Configure Tomcat users
  template:
    src: tomcat-users.xml
    dest: '/opt/tomcat/latest/conf/tomcat-users.xml'

- name: Change tomcat port
  template:
    src: server.xml
    dest: '/opt/tomcat/latest/conf/server.xml'

- name: Change manager context
  template:
    src: context_stock.xml
    dest: '/opt/tomcat/latest/webapps/manager/META-INF/context.xml'

- name: Change host-manager context
  template:
    src: context_host.xml
    dest: '/opt/tomcat/latest/webapps/host-manager/META-INF/context.xml'
